### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by Nemasix**
Modify my mistake on my author file

### CODE REVIEW

**Comment by yuchi** [comment]
Don’t worry, I’ll change it for you.

**Comment by yuchi** [comment]
I rebased your changes, that means that you should change your branch for the next translation.

**Comment by Nemasix** [comment]
Ok so i close this branch and I'll use development branch next time.

I'll try to translate the second article before the end of the week :)

**Comment by yuchi** [comment]
Great!

**Pull request closed without merging**
